services:
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ../instance/:/root/db/
    networks:
      - net

  app:
    build: ..
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
    volumes:
      - ../instance/:/app/instance/
    depends_on:
      - sqlite3
    networks:
      - net

networks:
  net:
    external: true
